# Generated by Django 4.1 on 2023-02-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platecom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produit',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prix',
            field=models.FloatField(default=0.0),
        ),
    ]
